@startuml



skinparam shadowing true


class Coleccion {
  - titulo: String
  - descripcion: String
  - fuente: Fuente
  - criterio: CriterioPertenencia
  + contiene(hecho: Hecho): boolean
}

class Administrador {
  - user: String
  - password: String
  + crearColeccion()
  + importarHecho(archivo: FuenteCSV)
}

enum Origen {
  CSV
  MANUAL
  CONTRIBUYENTE
}

class CriterioPertenencia {
  + cumple(hecho: Hecho): boolean
}

abstract class Fuente {
  + obtenerHechos(): List<Hecho>
}

class FuenteCSV {
  - path: string
  + obtenerHechos(): List<Hecho>
}
class SolicitudEliminacion {
  - hecho: Hecho
  - textoFundamentacion: String
  - estado: EstadoSolicitud
}

enum EstadoSolicitud {
  PENDIENTE
  ACEPTADA
  RECHAZADA
}
interface Contribuyente{}

class ContribuyenteIdentificado {
  - nombre: String
  - apellido: String
  - edad: int
}

class Visualizador {
  + navegarPorHechos(coleccion: Coleccion, filtro: Filtro)
}

enum Filtro {
  TITULO
  DESCRIPCION
  CATEGORIA
  LATITUD
  LONGITUD
  FECHA_ACONTECIMIENTO
  FECHA_CARGA
  ORIGEN
}

abstract class Hecho {
  - titulo: String
  - descripcion: String
  - categoria: String
  - latitud: Double
  - longitud: Double
  - fechaAcontecimiento: LocalDate
  - fechaCarga: LocalDate
  - origen: Origen
}

class HechoConMultimedia {
  - urls: List<String>
}

class HechoDeTexto{}


Administrador --> Coleccion
Administrador --> SolicitudEliminacion
Administrador ..|> Contribuyente

Coleccion --> Hecho
Coleccion --> Fuente
Coleccion --> CriterioPertenencia

Hecho --> Origen
HechoConMultimedia ..|> Hecho
HechoDeTexto ..|> Hecho

FuenteCSV ..|> Fuente

Contribuyente --> Hecho
Contribuyente --> SolicitudEliminacion
Contribuyente --> Filtro
ContribuyenteIdentificado ..|> Contribuyente
Visualizador ..|> Contribuyente

SolicitudEliminacion --> Hecho
SolicitudEliminacion --> EstadoSolicitud

@enduml
