@startuml

left to right direction

skinparam shadowing true

class Administrador {
  - user: String
  - password: String
  + crearColeccion()
  + importarHecho(archivo: FuenteCSV)
}

class Coleccion {
  - titulo: String
  - descripcion: String
  - fuente: Fuente
  - criterio: CriterioPertenencia
  + contiene(hecho: Hecho): boolean
}

abstract class Hecho {
  - titulo: String
  - descripcion: String
  - categoria: String
  - latitud: Double
  - longitud: Double
  - fechaAcontecimiento: LocalDate
  - fechaCarga: LocalDate
  - origen: Origen
}

class HechoConMultimedia {
  - urls: List<String>
}

class HechoDeTexto{}

enum Origen {
  CSV
  MANUAL
  CONTRIBUYENTE
}

interface CriterioPertenencia {
  + cumple(hecho: Hecho): boolean
}

class CriterioPorCategoriaYFecha {
  - categoria: String
  - desde: LocalDate
  - hasta: LocalDate
  + cumple(hecho: Hecho): boolean
}

abstract class Fuente {
  + obtenerHechos(): List<Hecho>
}

class FuenteCSV {
  - path: string
  + obtenerHechos(): List<Hecho>
}

interface Contribuyente{}

class ContribuyenteIdentificado {
  - nombre: String
  - apellido: String
  - edad: int
}

class Visualizador {
  + navegarPorHechos(coleccion: Coleccion, filtro: Filtro)
}

enum Filtro {
  TITULO
  DESCRIPCION
  CATEGORIA
  LATITUD
  LONGITUD
  FECHA_ACONTECIMIENTO
  FECHA_CARGA
  ORIGEN
}

class SolicitudEliminacion {
  - hecho: Hecho
  - textoFundamentacion: String
  - estado: EstadoSolicitud
}

enum EstadoSolicitud {
  PENDIENTE
  ACEPTADA
  RECHAZADA
}


Administrador --> Coleccion
Administrador --> SolicitudEliminacion

Coleccion --> Hecho
Coleccion --> Fuente
Coleccion --> CriterioPertenencia

Hecho --> Origen
HechoConMultimedia ..|> Hecho
HechoDeTexto ..|> Hecho

CriterioPorCategoriaYFecha ..|> CriterioPertenencia

FuenteCSV ..|> Fuente

Contribuyente --> Hecho
Contribuyente --> SolicitudEliminacion
ContribuyenteIdentificado ..|> Contribuyente
Visualizador ..|> Contribuyente
Visualizador --> Filtro

SolicitudEliminacion --> Hecho
SolicitudEliminacion --> EstadoSolicitud

@enduml
